---
title: "Movielens"
date: '`r Sys.time()`'
output:
  html_document:
    #code_folding: hide
    number_sections: yes
    toc: yes
    toc_depth: 3
---

```{r setup, include=FALSE}
library(scales)
library(tidyverse)
library(knitr)

# set plot theme
theme_set(theme_bw())
```

# Load and preview data

Read data from the `ratings.csv` file
```{r load-data}
ratings <- read_csv('ratings.csv',
                    col_names = c('user_id','movie_id','rating','timestamp'))
```
Read data from the `movies.tsv` file
```{r}
movies <- read_tsv('movies.tsv',
                    col_names = c('movie_id', 'title', 'genres'), quote = "")
```

Loaded `r format(object.size(ratings), units="Mb")` of ratings data, containing `r format(nrow(ratings), big.mark = ",")` ratings. Here's a preview:
```{r preview-data}
head(ratings) %>% kable()
```

# Summary statistics

```{r dist-ratings}
# plot the distribution of rating values (slide 21)
ratings %>%
  group_by(rating) %>%
  ggplot(aes(x = rating)) +
  scale_y_continuous(label = comma) +
  geom_histogram(bins = 10)
```

## Per-movie stats

```{r aggregate-by-movie}
# aggregate ratings by movie, computing mean and number of ratings
# hint: use the n() function for easy counting within a group
ratings %>%
  group_by(movie_id) %>%
  summarize(num_ratings = n(), average = mean(rating))

```

```{r dist-movie-popularity}
# plot distribution of movie popularity (= number of ratings the movie received)
# hint: try scale_x_log10() for a logarithmic x axis
ratings %>%
  group_by(movie_id) %>%
  summarize(num_ratings = n()) %>%
  ggplot(aes(x = num_ratings)) +
  scale_x_log10() +
  geom_histogram() +
  xlab("Number of Ratings") +
  ylab("Number of Movies")
  

```

```{r dist-mean-ratings-by-movie}
# plot distribution of mean ratings by movie (slide 23)
# hint: try geom_histogram and geom_density
ratings %>%
  group_by(movie_id) %>%
  summarize(count = n(), avg = mean(rating)) %>%
  ggplot(aes(x = avg)) +
  geom_density(fill = 'blue')
```

```{r cdf-movie-pop}
# rank movies by popularity and compute the cdf, or fraction of movies covered by the top-k moves (slide 25)
# hint: use dplyr's rank and arrange functions, and the base R sum and cumsum functions
# store the result in a new data frame so you can use it in creating figure 2 from the paper below

# plot the CDF of movie popularity
ratings %>%
  group_by(movie_id) %>%
  summarize(count=n()) %>% 
  arrange(desc(count)) %>%
  mutate(rank = rank(desc(count)), frac_ratings = cumsum(count)/sum(count)) %>%
  ggplot(aes(x = rank, y = frac_ratings)) +
  scale_y_continuous(label = percent) +
  geom_line()
```


# Per-user stats

```{r aggregate-by-user}
# aggregate ratings by user, computing mean and number of ratings
ratings %>%
  group_by(user_id) %>%
  summarize(rat_per_user = n(), avg = mean(rating))
  
```

```{r dist-user-activity}
# plot distribution of user activity (= number of ratings the user made)
# hint: try a log scale here
ratings %>%
  group_by(user_id) %>%
  summarize(num_ratings = n(), avg = mean(rating)) %>%
  ggplot(aes(x = num_ratings)) +
  scale_x_log10() +
  geom_histogram() +
  xlab("Number of Ratings") +
  ylab("Number of Users")
```

# Anatomy of the long tail

```{r long-tail}
# generate the equivalent of figure 2 of this paper:
# https://5harad.com/papers/long_tail.pdf

# Specifically, for the subset of users who rated at least 10 movies,
# produce a plot that shows the fraction of users satisfied (vertical
# axis) as a function of inventory size (horizontal axis). We will
# define "satisfied" as follows: an individual user is satisfied p% of
# the time at inventory of size k if at least p% of the movies they
# rated are contained in the top k most popular movies. As in the
# paper, produce one curve for the 100% user satisfaction level and
# another for 90%---do not, however, bother implementing the null
# model (shown in the dashed lines).
users_rated_at_least_10 <- ratings %>%
  group_by(user_id) %>%
  filter(n() >= 10) %>%
  ungroup()

movies_by_rank <- ratings %>%
  group_by(movie_id) %>%
  summarize(num_ratings = n()) %>%
  arrange(desc(num_ratings)) %>% 
  mutate(rank = rank(desc(num_ratings)))

joined <- inner_join(users_rated_at_least_10, movies_by_rank)

#lowest rank means rank is a high number
lowest_rank_per_user_100 <- joined %>%
  group_by(user_id) %>%
  summarize(rank_100 = max(rank))

# the movie percentage rating then filtered to get the movie closest to 90%
percentage_90 <- joined %>%
  group_by(user_id) %>%
  mutate(percentile = percent_rank(rank)) %>% 
  filter(percentile >= .9) %>% 
  summarize(rank_90 = min(rank))

ranks_90_100 <- inner_join(lowest_rank_per_user_100, percentage_90)

# get the number of users
num_users <- users_rated_at_least_10 %>% select(user_id) %>% unique() %>% count()


rank_100_data <- ranks_90_100 %>%
  arrange(rank_100) %>% 
  mutate(row_num = row_number()) %>% 
  group_by(rank_100) %>%
  summarize(num_users_happy = max(row_num)/ num_users$n)


rank_90_data <- ranks_90_100 %>%
  arrange(rank_90) %>%
  mutate(row_num = row_number()) %>%
  group_by(rank_90) %>%
  summarize(num_users_90_pct_happy = max(row_num)/num_users$n )

rank_100_data %>%
  ggplot() +
  geom_line(aes(x = rank_100, y = num_users_happy)) +
  geom_line(data = rank_90_data, aes(x = rank_90, y = num_users_90_pct_happy)) +
  scale_y_continuous(label = percent) +
  labs(x = 'Percentage of Users Satisfied', y = 'Inventory Size', title = 'The Anatomy of the Long Tail')
  

```
